---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: default
  labels:
    app: hello-app
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-app
      type: backend
  template:
    metadata:
      labels:
        app: hello-app
        type: backend
    spec:
      containers:
      - name: hello-app
        image: eslamt/node-app:latest
        ports:
        - containerPort: 3000
