---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: default
  labels:
    app: hello-app
    type: backend
spec:
  selector:
    app: hello-app
    type: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer